spring:
  application:
    name: dictionary-service-grpc

  datasource:
    url: jdbc:postgresql://localhost:5432/db?currentSchema=dictionary
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/db?currentSchema=dictionary
    password: password
    user: postgres

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui
  enable-kotlin: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  info:
    os:
      enabled: true
    java:
      enabled: true
  metrics:
    enable:
      tomcat: true
      jvm: true
      process: true
      hikaricp: true
      system: true
      jdbc: true
      logback: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      slo:
        http.server.requests: 1ms, 10ms, 50ms
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    loggers:
      enabled: true
    metrics:
      enabled: true
      distribution:
        slo:
          http:
            server:
              requests: 1ms, 10ms, 50ms
        percentiles-histogram:
          http:
            server:
              requests: true
        percentiles:
          http:
            server:
              requests: 0.5, 0.9, 0.95, 0.99, 0.999
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"